#browsers

#themes

App_Install__wine=1
App_Install__wine_mono=1
App_Install__7_zip=1
App_Install__adwaita_theme=1
App_Install__anydesk=1
App_Install__audacity=1
App_Install__biglybt=1
App_Install__bleachbit=1
App_Install__brave=1
App_Install__calibre=1
App_Install__discord=1
App_Install__dropbox=1
App_Install__filezilla=1
App_Install__firefox=1
App_Install__font_dejavu=1
App_Install__git=1
App_Install__gimp=1
App_Install__gnome_terminal=1
App_Install__google_chrome=1
App_Install__handbrake=1
App_Install__heroic_launcher=1
App_Install__jitsi_meet=1
App_Install__keepass=1
App_Install__libreoffice=1
App_Install__librewolf=1
App_Install__minecraft_launcher=1
App_Install__notepadqq=1
App_Install__notepadPlusPlus=1
App_Install__numlockx=1
App_Install__obs_studio=1
App_Install__opera=1
App_Install__paradox_launcher=1
App_Install__pcloud=1
App_Install__peazip=1
App_Install__pidgin=1
App_Install__scrcpy=1
App_Install__session=1
App_Install__signal=1
App_Install__steam=1
App_Install__teamviewer=1
App_Install__thorium=1
App_Install__torbrowser=1
App_Install__thunderbird=1
App_Install__tigervnc=1
App_Install__virtualbox=1
App_Install__visual_studio_code=1
App_Install__vlc=1
App_Install__vuze=1
App_Install__waterfox=1
App_Install__wire=1

#bash <(curl -L https://raw.githubusercontent.com/TheSuperGiant/Arch/refs/heads/Arch/2.sh) "<(curl -L 'https://raw.githubusercontent.com/007BS/arch/refs/heads/Arch/config.sh')"